version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: adote-nginx
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: adote-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: adote
      MYSQL_USER: adote
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adote-app
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel
